# Generated by Django 4.2.3 on 2023-08-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesspage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
