# Generated by Django 4.2.3 on 2023-08-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_address1_alter_user_address2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(default='birthday', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='nickname', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password1',
            field=models.CharField(default='password1', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password2',
            field=models.CharField(default='password2', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='phone', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='usertype', max_length=10),
        ),
    ]
